lst = ["Venus", "Earth", "Jupiter", "Saturn", "Neptune"]
print("Length:", len(lst))
print("First element:", lst[0])
print("Last element:", lst[-1])
lst.append("Earth")
print("Updated list:", lst)
lst.remove("Saturn")
print("Updated list:", lst)
lst.sort()
print("Sorted list:", lst)
lst.pop(1)
print("Updated list:", lst)
lst.reverse()
print("Reversed list (distance):", lst)
print("Double list:", lst*2)
lst=lst[:4]
print("Sliced list :", lst)
lst.clear()
print("Updated list:", lst)